name: Homework 1 Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build
        working-directory: homework/01-guarantees/test
        run: cargo build --release

      - name: Run tests
        working-directory: homework/01-guarantees/test
        run: cargo run --release -- -m 100 -o
